include: package:very_good_analysis/analysis_options.5.1.0.yaml
analyzer:
  errors:
    lines_longer_than_80_chars: ignore
  exclude:
    - build/**
    - .dart_tool/**
    - node_modules/**      # Se estiver usando Flutter Web com pacotes JS
    - ios/**
    - android/**
    - web/**
linter:
  rules:
    file_names: false
    

formatter:
  page_width: 120
  trailing_commas: preserve

